#ifndef PAGEINDEX_H
#define PAGEINDEX_H

enum PageIndex
{
    PAGE_HOME = 0,
    PAGE_LOGIN,
    PAGE_SETTING,
    PAGE_PULSEMODE,
    PAGE_PROTOCOLSELECT,
    PAGE_NEWCUSTOMPROTOCOL,
    PAGE_READYFORSURGERY,
    PAGE_SURGERYDATA,
    PAGE_USAGEAREA,
    PAGE_SYSTEMUSAGES,
    PAGE_RENTALINFO,
    PAGE_SERVICEENGINEER,
    PAGE_CALIBRATION,
    PAGE_SETDATETIME,
    PAGE_CHANGEPASSWORD
};

#endif // PAGEINDEX_H
